const mongoose = require('mongoose');
const College  = require('./models/College');
require('dotenv').config();

const colleges = [
  { id:1, name:"IIT Delhi", abbr:"IIT-D", location:"New Delhi, Delhi", state:"Delhi", type:"Engineering", rating:"NIRF #4", fees:238000, feesDisplay:"₹2.38L/yr", exam:"JEE Advanced", rank:"NIRF Engg #4", established:"1961", type2:"Government", affiliation:"Autonomous – IIT Act", about:"Indian Institute of Technology Delhi is one of India's premier engineering institutions, ranked #4 overall by NIRF 2024.", courses:["B.Tech CSE","B.Tech EE","B.Tech Mech","B.Tech Civil","B.Tech Chemical","M.Tech AI","M.Tech VLSI","MBA","PhD"], facilities:["Library","Hostel","Sports Complex","Labs","Cafeteria","Wi-Fi","Medical Centre","Auditorium"], phone:"+91-11-26591000", email:"ugadmission@admin.iitd.ac.in", website:"home.iitd.ac.in" },
  { id:2, name:"AIIMS New Delhi", abbr:"AIIMS", location:"New Delhi, Delhi", state:"Delhi", type:"Medical", rating:"NIRF #1", fees:1628, feesDisplay:"₹1,628/yr", exam:"NEET", rank:"NIRF Medical #1", established:"1956", type2:"Government", affiliation:"Autonomous – AIIMS Act", about:"AIIMS New Delhi is India's top medical institution for 4 consecutive years per NIRF 2024. Annual fee of just ₹1,628 makes it one of the most affordable premier institutions.", courses:["MBBS","MD General Medicine","MS Surgery","B.Sc Nursing","M.Sc Biochemistry","PhD Medical"], facilities:["Hospital","Research Labs","Hostel","Library","Cafeteria","Sports Ground"], phone:"+91-11-26588500", email:"director@aiims.edu", website:"aiims.edu" },
  { id:3, name:"IIM Ahmedabad", abbr:"IIM-A", location:"Ahmedabad, Gujarat", state:"Gujarat", type:"Management", rating:"NIRF #1", fees:2300000, feesDisplay:"₹23L/yr", exam:"CAT", rank:"NIRF Mgmt #1", established:"1961", type2:"Government", affiliation:"Autonomous – IIM Act", about:"IIM Ahmedabad is India's #1 business school per NIRF 2024, known for rigorous case-study based learning and influential alumni network.", courses:["MBA","PGP","Executive MBA","PhD Management","MBA Finance","MBA Marketing"], facilities:["Library","Hostel","Sports Complex","Auditorium","Cafeteria","Wi-Fi"], phone:"+91-79-66324000", email:"pgpchair@iima.ac.in", website:"iima.ac.in" },
  { id:4, name:"NLU Delhi", abbr:"NLU-D", location:"New Delhi, Delhi", state:"Delhi", type:"Law", rating:"NIRF #2", fees:180000, feesDisplay:"₹1.8L/yr", exam:"CLAT", rank:"NIRF Law #2", established:"2008", type2:"Government", affiliation:"Autonomous – NLU Act", about:"National Law University Delhi is ranked #2 in Law by NIRF 2024, producing outstanding legal professionals and academics.", courses:["BA LLB","LLM","PhD Law","Masters Business Law","PG Diploma Cyber Law"], facilities:["Moot Court","Library","Hostel","Cafeteria","Wi-Fi","Sports Ground"], phone:"+91-11-28034257", email:"info@nludelhi.ac.in", website:"nludelhi.ac.in" },
  { id:5, name:"IIT Bombay", abbr:"IIT-B", location:"Mumbai, Maharashtra", state:"Maharashtra", type:"Engineering", rating:"NIRF #3", fees:220750, feesDisplay:"₹2.2L/yr", exam:"JEE Advanced", rank:"NIRF Engg #3", established:"1958", type2:"Government", affiliation:"Autonomous – IIT Act", about:"IIT Bombay is ranked #3 in Engineering by NIRF 2024, known for strong industry connections and thriving startup culture.", courses:["B.Tech CSE","B.Tech Mech","M.Tech AI","B.Tech Chemical","B.Tech Aerospace","MBA","PhD"], facilities:["Library","Hostel","Olympic Pool","Labs","Cafeteria","Wi-Fi","Auditorium"], phone:"+91-22-25722545", email:"registrar@iitb.ac.in", website:"iitb.ac.in" },
  { id:6, name:"Amity University", abbr:"AMU", location:"Noida, Uttar Pradesh", state:"Uttar Pradesh", type:"Engineering", rating:"NIRF 51-100", fees:350000, feesDisplay:"₹3.5L/yr", exam:"JEE Main", rank:"NIRF Rank 51-100", established:"2005", type2:"Private", affiliation:"UGC Recognised", about:"Amity University is one of India's largest private universities with strong industry tie-ups and placement support.", courses:["B.Tech CSE","B.Tech AI & ML","BBA","MBA","B.Sc Biotechnology","B.Tech ECE"], facilities:["Library","Hostel","Sports Complex","Labs","Cafeteria","Wi-Fi","Swimming Pool"], phone:"+91-120-4392000", email:"admissions@amity.edu", website:"amity.edu" },
  { id:7, name:"Presidency University", abbr:"PU", location:"Kolkata, West Bengal", state:"West Bengal", type:"Arts", rating:"NIRF Top 50", fees:12000, feesDisplay:"₹12K/yr", exam:"CUET", rank:"NIRF Colleges Top 50", established:"1817", type2:"Government", affiliation:"UGC Recognised", about:"Presidency University Kolkata, established in 1817, has produced Nobel laureates including Amartya Sen.", courses:["B.Sc Physics","B.Sc Chemistry","B.A. History","B.A. English","M.Sc Chemistry","PhD"], facilities:["Historic Library","Hostel","Science Labs","Cafeteria","Sports Ground","Auditorium"], phone:"+91-33-22413893", email:"president@presiuniv.ac.in", website:"presiuniv.ac.in" },
  { id:8, name:"BITS Pilani", abbr:"BITS", location:"Pilani, Rajasthan", state:"Rajasthan", type:"Engineering", rating:"NIRF #16", fees:562050, feesDisplay:"₹5.6L/yr", exam:"BITSAT", rank:"NIRF Engg #16", established:"1964", type2:"Private (Deemed)", affiliation:"Autonomous", about:"BITS Pilani ranked #16 in Engineering NIRF 2024, known for Practice School program and strong Silicon Valley alumni network.", courses:["B.Tech CSE","B.Tech Mech","B.Pharma","M.Tech","B.Tech EEE","M.Sc Chemistry"], facilities:["Library","Hostel","Sports Complex","Labs","Cafeteria","Wi-Fi","Medical Centre"], phone:"+91-1596-242192", email:"admissions@pilani.bits-pilani.ac.in", website:"bits-pilani.ac.in" },
  { id:9, name:"Kasturba Medical College", abbr:"KMC", location:"Manipal, Karnataka", state:"Karnataka", type:"Medical", rating:"NIRF #27", fees:1200000, feesDisplay:"₹12L/yr", exam:"NEET", rank:"NIRF Medical #27", established:"1953", type2:"Private (Deemed)", affiliation:"Manipal Academy", about:"Kasturba Medical College ranked #27 in Medical by NIRF 2024, offering world-class clinical training.", courses:["MBBS","BDS","B.Sc Nursing","MD General Medicine","MS Surgery","PhD Medical"], facilities:["Hospital","Research Labs","Hostel","Library","Simulation Centre","Sports Ground"], phone:"+91-820-2922000", email:"info@manipal.edu", website:"manipal.edu/kmc" },
  { id:10, name:"Anna University", abbr:"AU", location:"Chennai, Tamil Nadu", state:"Tamil Nadu", type:"Engineering", rating:"NIRF #1", fees:80000, feesDisplay:"₹80K/yr", exam:"JEE Main", rank:"NIRF State Univ #1", established:"1978", type2:"Government", affiliation:"State University", about:"Anna University is ranked #1 among State Public Universities by NIRF 2024, one of the largest technical universities in India.", courses:["B.Tech CSE","B.Tech Civil","B.Tech Mech","B.Tech IT","M.E. CSE","MBA","PhD"], facilities:["Library","Hostel","Labs","Sports Ground","Cafeteria","Wi-Fi","Auditorium"], phone:"+91-44-22357004", email:"registrar@annauniv.edu", website:"annauniv.edu" },
  { id:11, name:"Delhi University", abbr:"DU", location:"New Delhi, Delhi", state:"Delhi", type:"Arts", rating:"NIRF #10", fees:15000, feesDisplay:"₹15K/yr", exam:"CUET", rank:"NIRF University #10", established:"1922", type2:"Government", affiliation:"Central University", about:"University of Delhi is ranked #10 among Universities by NIRF 2024 with over 90 colleges and 300,000+ students.", courses:["B.A. English","B.A. Economics","B.Com","B.Sc Maths","LLB","M.Com","PhD"], facilities:["Library","Hostel","Sports Complex","Labs","Cafeteria","Wi-Fi","Medical Centre"], phone:"+91-11-27667853", email:"web@du.ac.in", website:"du.ac.in" },
  { id:12, name:"Jadavpur University", abbr:"JU", location:"Kolkata, West Bengal", state:"West Bengal", type:"Engineering", rating:"NIRF #2", fees:25000, feesDisplay:"₹25K/yr", exam:"JEE Main", rank:"NIRF State Univ #2", established:"1905", type2:"Government", affiliation:"State University", about:"Jadavpur University is ranked #2 among State Public Universities by NIRF 2024.", courses:["B.Tech CSE","B.Tech EE","B.Tech Mech","M.Tech CSE","B.A. English","PhD"], facilities:["Library","Hostel","Labs","Sports Ground","Cafeteria","Auditorium"], phone:"+91-33-24146000", email:"registrar@jadavpuruniversity.in", website:"jadavpuruniversity.in" },
  { id:13, name:"Banaras Hindu University", abbr:"BHU", location:"Varanasi, Uttar Pradesh", state:"Uttar Pradesh", type:"Arts", rating:"NIRF #8", fees:8000, feesDisplay:"₹8K/yr", exam:"CUET", rank:"NIRF University #8", established:"1916", type2:"Government", affiliation:"Central University", about:"BHU is ranked #8 among Universities by NIRF 2024, one of Asia's largest residential universities on a 1300-acre campus.", courses:["B.A. Sanskrit","B.Sc Physics","MBBS","B.Tech CSE","LLB","B.Ed","PhD"], facilities:["Library","Hostel","Hospital","Sports Complex","Labs","Cafeteria","Temple"], phone:"+91-542-2307221", email:"registrar@bhu.ac.in", website:"bhu.ac.in" },
  { id:14, name:"VIT Vellore", abbr:"VIT", location:"Vellore, Tamil Nadu", state:"Tamil Nadu", type:"Engineering", rating:"NIRF #11", fees:198000, feesDisplay:"₹1.98L/yr", exam:"JEE Main", rank:"NIRF Engg #11", established:"1984", type2:"Private (Deemed)", affiliation:"Autonomous", about:"VIT Vellore is ranked #11 in Engineering by NIRF 2024 with students from 50+ countries.", courses:["B.Tech CSE","B.Tech AI & ML","B.Tech ECE","B.Tech Mech","MBA","M.Tech CSE","PhD"], facilities:["Library","Hostel","Sports Complex","Labs","Cafeteria","Wi-Fi","Innovation Centre"], phone:"+91-416-2202020", email:"admissions@vit.ac.in", website:"vit.ac.in" },
  { id:15, name:"SRM Institute", abbr:"SRM", location:"Chennai, Tamil Nadu", state:"Tamil Nadu", type:"Engineering", rating:"NIRF #21", fees:250000, feesDisplay:"₹2.5L/yr", exam:"JEE Main", rank:"NIRF Engg #21", established:"1985", type2:"Private (Deemed)", affiliation:"Autonomous", about:"SRM Institute ranked #21 in Engineering by NIRF 2024 with strong industry partnerships.", courses:["B.Tech CSE","B.Tech ECE","B.Tech Mech","MBA","B.Sc Nursing","M.Tech AI","PhD"], facilities:["Library","Hostel","Sports Complex","Labs","Cafeteria","Wi-Fi","Medical Centre"], phone:"+91-44-27417000", email:"admissions@srmist.edu.in", website:"srmist.edu.in" },
  { id:16, name:"Osmania University", abbr:"OU", location:"Hyderabad, Telangana", state:"Telangana", type:"Arts", rating:"NIRF 51-100", fees:18000, feesDisplay:"₹18K/yr", exam:"CUET", rank:"NIRF Univ 51-100", established:"1918", type2:"Government", affiliation:"State University", about:"Osmania University established in 1918 is one of India's oldest universities with a beautiful heritage campus.", courses:["B.A. Economics","B.Com","B.Sc Chemistry","LLB","M.A. Telugu","M.Com","PhD"], facilities:["Historic Library","Hostel","Labs","Sports Ground","Cafeteria","Museum"], phone:"+91-40-27098090", email:"registrar@osmania.ac.in", website:"osmania.ac.in" },
  { id:17, name:"Hyderabad Central Univ", abbr:"HCU", location:"Hyderabad, Telangana", state:"Telangana", type:"Arts", rating:"NIRF #14", fees:12000, feesDisplay:"₹12K/yr", exam:"CUET", rank:"NIRF University #14", established:"1974", type2:"Government", affiliation:"Central University", about:"University of Hyderabad is ranked #14 among Universities by NIRF 2024, a premier central university known for research.", courses:["M.A. English","M.Sc Physics","MBA","M.Tech CSE","M.A. Linguistics","PhD"], facilities:["Library","Hostel","Research Labs","Sports Complex","Cafeteria","Wi-Fi"], phone:"+91-40-23133000", email:"registrar@uohyd.ac.in", website:"uohyd.ac.in" },
  { id:18, name:"NIT Trichy", abbr:"NIT-T", location:"Tiruchirappalli, Tamil Nadu", state:"Tamil Nadu", type:"Engineering", rating:"NIRF #8", fees:154200, feesDisplay:"₹1.54L/yr", exam:"JEE Main", rank:"NIRF Engg #8", established:"1964", type2:"Government", affiliation:"Autonomous – NIT Act", about:"NIT Trichy is ranked #8 in Engineering by NIRF 2024 and India's top National Institute of Technology.", courses:["B.Tech CSE","B.Tech Mech","B.Tech Civil","B.Tech EEE","M.Tech CSE","MBA","PhD"], facilities:["Library","Hostel","Sports Complex","Labs","Cafeteria","Wi-Fi","Medical Centre"], phone:"+91-431-2503000", email:"admissions@nitt.edu", website:"nitt.edu" },
  { id:19, name:"Symbiosis International", abbr:"SIU", location:"Pune, Maharashtra", state:"Maharashtra", type:"Management", rating:"NIRF #21", fees:600000, feesDisplay:"₹6L/yr", exam:"CAT", rank:"NIRF Mgmt #21", established:"2002", type2:"Private (Deemed)", affiliation:"Autonomous", about:"Symbiosis International ranked #21 in Management by NIRF 2024 with students from 80+ countries.", courses:["MBA","BBA","LLB","B.Sc IT","M.Sc Data Science","MBA HR","MBA Finance"], facilities:["Library","Hostel","Sports Complex","Labs","Cafeteria","Wi-Fi","International Centre"], phone:"+91-20-28116226", email:"siu@siu.edu.in", website:"siu.edu.in" },
  { id:20, name:"Jamia Millia Islamia", abbr:"JMI", location:"New Delhi, Delhi", state:"Delhi", type:"Engineering", rating:"NIRF #3", fees:30000, feesDisplay:"₹30K/yr", exam:"JEE Main", rank:"NIRF University #3", established:"1920", type2:"Government", affiliation:"Central University", about:"Jamia Millia Islamia is ranked #3 among Universities by NIRF 2024 with roots in India's freedom movement.", courses:["B.Tech CSE","B.Tech ECE","B.A. Mass Comm","LLB","B.Ed","MBA","PhD"], facilities:["Library","Hostel","Sports Ground","Labs","Cafeteria","Wi-Fi","Museum"], phone:"+91-11-26981717", email:"info@jmi.ac.in", website:"jmi.ac.in" },
  { id:21, name:"Calcutta Medical College", abbr:"CMC", location:"Kolkata, West Bengal", state:"West Bengal", type:"Medical", rating:"NIRF #15", fees:50000, feesDisplay:"₹50K/yr", exam:"NEET", rank:"NIRF Medical #15", established:"1835", type2:"Government", affiliation:"WB Health Sciences Univ", about:"Calcutta Medical College established in 1835 is one of Asia's oldest medical institutions, ranked #15 in Medical NIRF 2024.", courses:["MBBS","MD General Medicine","MS Surgery","B.Sc Nursing","MD Psychiatry","PhD Medical"], facilities:["Hospital","Research Labs","Hostel","Library","Anatomy Museum","Sports Ground"], phone:"+91-33-22551948", email:"principal@cmckolkata.in", website:"cmckolkata.in" },
  { id:22, name:"Nalsar Univ of Law", abbr:"NALSAR", location:"Hyderabad, Telangana", state:"Telangana", type:"Law", rating:"NIRF #3", fees:160000, feesDisplay:"₹1.6L/yr", exam:"CLAT", rank:"NIRF Law #3", established:"1998", type2:"Government", affiliation:"Autonomous – AP Act", about:"NALSAR University of Law ranked #3 in Law by NIRF 2024, known for moot court excellence.", courses:["BA LLB","LLM","MBA Law","PhD Law","PG Diploma Cyber Law","LLM IPR"], facilities:["Moot Court","Library","Hostel","Cafeteria","Wi-Fi","Sports Ground"], phone:"+91-40-23498104", email:"admissions@nalsar.ac.in", website:"nalsar.ac.in" },
  { id:23, name:"IIT Madras", abbr:"IIT-M", location:"Chennai, Tamil Nadu", state:"Tamil Nadu", type:"Engineering", rating:"NIRF #1", fees:234750, feesDisplay:"₹2.35L/yr", exam:"JEE Advanced", rank:"NIRF Engg #1", established:"1959", type2:"Government", affiliation:"Autonomous – IIT Act", about:"IIT Madras is ranked #1 in Engineering by NIRF 2024 for 6 consecutive years and #1 Overall in India.", courses:["B.Tech CSE","B.Tech Aerospace","B.Tech Ocean Engg","B.Tech Mech","M.Tech AI","MBA","PhD"], facilities:["Library","Hostel","Research Park","Sports Complex","Cafeteria","Wi-Fi","Innovation Hub"], phone:"+91-44-22574000", email:"registrar@iitm.ac.in", website:"iitm.ac.in" },
  { id:24, name:"Christ University", abbr:"CU", location:"Bengaluru, Karnataka", state:"Karnataka", type:"Management", rating:"NIRF 51-100", fees:180000, feesDisplay:"₹1.8L/yr", exam:"CAT", rank:"NIRF Rank 51-100", established:"1969", type2:"Private (Deemed)", affiliation:"Autonomous", about:"Christ University Bengaluru is a leading private deemed university known for holistic education.", courses:["BBA","MBA","B.Com","BA Economics","B.Sc Psychology","MA English","PhD"], facilities:["Library","Hostel","Sports Complex","Labs","Cafeteria","Wi-Fi","Chapel"], phone:"+91-80-40129100", email:"admissions@christuniversity.in", website:"christuniversity.in" },
  { id:25, name:"Manipal Inst of Tech", abbr:"MIT", location:"Manipal, Karnataka", state:"Karnataka", type:"Engineering", rating:"NIRF #41", fees:420000, feesDisplay:"₹4.2L/yr", exam:"JEE Main", rank:"NIRF Engg #41", established:"1957", type2:"Private (Deemed)", affiliation:"Manipal Academy", about:"Manipal Institute of Technology ranked #41 in Engineering NIRF 2024, offering futuristic programs in AI and Robotics.", courses:["B.Tech CSE","B.Tech AI","B.Tech Robotics","B.Tech ECE","M.Tech CSE","MBA Tech","PhD"], facilities:["Library","Hostel","Sports Complex","Robotics Lab","Cafeteria","Wi-Fi","Innovation Studio"], phone:"+91-820-2923000", email:"admissions@manipal.edu", website:"manipal.edu/mit" }
];

async function seedDB() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ MongoDB Connected!');
    await College.deleteMany({});
    console.log('🗑️ Old data cleared');
    await College.insertMany(colleges);
    console.log('✅ 25 colleges added to MongoDB!');
    mongoose.connection.close();
  } catch (err) {
    console.log('❌ Error:', err);
  }
}

seedDB();